import os
import math

while True:
    print("\n")
    print("="*30)
    print("Pilih Bentuk Bangun Datar")
    print("="*30)
    print("1. Segitiga")
    print("2. Persegi")
    print("3. Keluar")
    print("-"*30)
    print("\n")
    i = (input("Masukan pilihan anda : "))
    if i == "1":
        os.system('cls')
        print("="*30)
        print("Pilih Jenis Segitiga")
        print("="*30)
        print("1. Segitiga sama kaki")
        print("2. Segitiga sama sisi")
        print("3. Segitiga sembarang")
        print("-"*30)
        print("\n")
        x = (input("Masukan pilihan anda : "))
        if x == "1":
            os.system('cls')
            print("="*30)
            print("Pilih Jenis Perhitungan")
            print("="*30)
            print("1. Hitung luas")
            print("2. Hitung keliling")
            print("-"*30)
            print("\n")
            v = (input("Masukan pilihan anda : "))
            if v == "1":
                os.system('cls')
                alas = int(input("Masukan alas segitiga : "))
                tinggi = int(input("Masukan tinggi segitiga : "))
                hasil = 1/2 * alas * tinggi
                print("="*30)
                print(f"hasil anda adalah = {int(hasil)}")
                print("-"*30)
                print("\n")
                input("Tekan tombol enter untuk melanjutkan...")
            elif v == "2":
                os.system('cls')
                sisi_1 = int(input("Masukan sisi pertama segitiga : "))
                sisi_2= int(input("Masukan sisi kedua segitiga : "))
                sisi_3 = int(input("Masukan sisi ketiga segitiga : "))
                hasil = sisi_1 + sisi_2 + sisi_3
                print("="*30)
                print(f"hasil anda adalah = {int(hasil)}")
                print("-"*30)
                print("\n")
                input("Tekan tombol enter untuk melanjutkan...")
            else :
                os.system('cls')
                print("Input anda Invalid!")
                print("\n")
                input("Tekan tombol enter untuk melanjutkan...")
        elif x == "2":
            os.system('cls')
            print("="*30)
            print("Pilih Jenis Perhitungan")
            print("="*30)
            print("1. Hitung luas")
            print("2. Hitung keliling")
            print("-"*30)
            print("\n")
            v = (input("Masukan pilihan anda : "))
            if v == "1":
                os.system('cls')
                alas = int(input("Masukan alas segitiga : "))
                tinggi = int(input("Masukan tinggi segitiga : "))
                hasil = 1/2 * alas * tinggi
                print("="*30)
                print(f"hasil anda adalah = {int(hasil)}")
                print("-"*30)
                print("\n")
                input("Tekan tombol enter untuk melanjutkan...")
            elif v == "2":
                os.system('cls')
                sisi_1 = int(input("Masukan sisi pertama segitiga : "))
                sisi_2= int(input("Masukan sisi kedua segitiga : "))
                sisi_3 = int(input("Masukan sisi ketiga segitiga : "))
                hasil = sisi_1 + sisi_2 + sisi_3
                print("="*30)
                print(f"hasil anda adalah = {int(hasil)}")
                print("-"*30)
                print("\n")
                input("Tekan tombol enter untuk melanjutkan...")
            else :
                os.system('cls')
                print("Input anda Invalid!")
                print("\n")
                input("Tekan tombol enter untuk melanjutkan...")
        elif x == "3":
            os.system('cls')
            print("="*30)
            print("Pilih Jenis Perhitungan")
            print("="*30)
            print("1. Hitung luas")
            print("2. Hitung keliling")
            print("-"*30)
            print("\n")
            v = (input("Masukan pilihan anda : "))
            if v == "1":
                os.system('cls')
                sisi_1 = int(input("Masukan sisi pertama segitiga : "))
                sisi_2= int(input("Masukan sisi kedua segitiga : "))
                sisi_3 = int(input("Masukan sisi ketiga segitiga : "))
                s = (sisi_1 + sisi_2 + sisi_3) / 2
                hasil = math.sqrt(s*(s - sisi_1)*(s - sisi_2)*(s - sisi_3))
                print("="*30)
                print(f"hasil anda adalah = {int(hasil)}")
                print("-"*30)
                print("\n")
                input("Tekan tombol enter untuk melanjutkan...")
            elif v == "2":
                os.system('cls')
                sisi_1 = int(input("Masukan sisi pertama segitiga : "))
                sisi_2= int(input("Masukan sisi kedua segitiga : "))
                sisi_3 = int(input("Masukan sisi ketiga segitiga : "))
                hasil = sisi_1 + sisi_2 + sisi_3
                print("="*30)
                print(f"hasil anda adalah = {int(hasil)}")
                print("-"*30)
                print("\n")
                input("Tekan tombol enter untuk melanjutkan...")
            else :
                os.system('cls')
                print("Input anda Invalid!")
                print("\n")
                input("Tekan tombol enter untuk melanjutkan...")
        else :
                os.system('cls')
                print("Input anda Invalid!")
                print("\n")
                input("Tekan tombol enter untuk melanjutkan...")
    elif i == "2":
        os.system('cls')
        print("="*30)
        print("Pilih Jenis Persegi")
        print("="*30)
        print("1. Bujur sangkar")
        print("2. Persegi panjang")
        print("-"*30)
        print("\n")
        x = (input("Masukan pilihan anda : "))
        if x == "1":
            os.system('cls')
            print("="*30)
            print("Pilih Jenis Perhitungan")
            print("="*30)
            print("1. Hitung luas")
            print("2. Hitung keliling")
            print("-"*30)
            print("\n")
            v = (input("Masukan pilihan anda : "))
            if v == "1":
                os.system('cls')
                sisi = int(input("Masukan sisi bujur sangkar: "))
                hasil = sisi * sisi
                print("="*30)
                print(f"Hasil akhirnya adalah = {int(hasil)}")
                print("-"*30)
                print("\n")
                input("Tekan tombol enter untuk melanjutkan...")
            elif v == "2":
                os.system('cls')
                sisi = int(input("Masukan sisi bujur sangkar : "))
                hasil = sisi * 4
                print("="*30)
                print(f"hasil anda adalah = {int(hasil)}")
                print("-"*30)
                print("\n")
                input("Tekan tombol enter untuk melanjutkan...")
            else :
                os.system('cls')
                print("Input anda Invalid!")
                print("\n")
                input("Tekan tombol enter untuk melanjutkan...")
        elif x == "2":
            os.system('cls')
            print("="*30)
            print("Pilih Jenis Perhitungan")
            print("="*30)
            print("1. Hitung luas")
            print("2. Hitung keliling")
            print("-"*30)
            print("\n")
            v = (input("Masukan pilihan anda : "))
            if v == "1":
                os.system('cls')
                panjang = int(input("Masukan panjang : "))
                lebar = int(input("Masukan lebar : "))
                hasil = panjang * lebar
                print("="*30)
                print(f"Hasil akhirnya adalah = {int(hasil)}")
                print("-"*30)
                print("\n")
                input("Tekan tombol enter untuk melanjutkan...")
            elif v == "2":
                os.system('cls')
                panjang = int(input("Masukan panjang : "))
                lebar = int(input("Masukan lebar : "))
                hasil = (panjang + lebar) * 2
                print("="*30)
                print(f"hasil anda adalah = {int(hasil)}")
                print("-"*30)
                print("\n")
                input("Tekan tombol enter untuk melanjutkan...")
            else :
                os.system('cls')
                print("Input anda Invalid!")
                print("\n")
                input("Tekan tombol enter untuk melanjutkan...")
        else :
                os.system('cls')
                print("Input anda Invalid!")
                print("\n")
                input("Tekan tombol enter untuk melanjutkan...")
    elif i == "3":
        os.system('cls')
        print("Terimakasih sudah menggunakan program ini :)")
        print("="*45)
        print("\n")
        break
    else :
                os.system('cls')
                print("Input anda Invalid!")
                print("\n")
                input("Tekan tombol enter untuk melanjutkan...")
        

    
